
language: java
dist: xenial
jdk:
  - openjdk11

script:
  - ./gradlew clean build check test
after_success:
  - ./gradlew -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2" jacocoTestReport coveralls



